# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration
client_id = "19d4f2ef1d1e42ee8e32766f2f2a3c96"
name = "Ciwi.ai:PD(Test)"
handle = "ciwi-ai-pdtest"
application_url = "https://descriptionfd.onrender.com"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_locales,read_products,read_themes,write_products"

[auth]
redirect_urls = [
  "https://descriptionfd.onrender.com/auth/callback",
  "https://descriptionfd.onrender.com/auth/shopify/callback",
  "https://descriptionfd.onrender.com/api/auth/callback"
]

[webhooks]
api_version = "2025-04"

[[webhooks.subscriptions]]
topics = ["app_purchases_one_time/update", "app/uninstalled"]
uri = "/webhooks"
compliance_topics = [
  "customers/data_request",
  "customers/redact",
  "shop/redact"
]

[pos]
embedded = false
