# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration
client_id = "b56a502400fe53e1f4cdfdb684929d2b"
name = "Ciwi.ai:AI product"
handle = "ciwi-ai-ai-product"
application_url = "https://descriptionfdprod.onrender.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "ciwishop.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_locales,read_products,read_themes,write_products"

[auth]
redirect_urls = [
  "https://descriptionfdprod.onrender.com/auth/callback",
  "https://descriptionfdprod.onrender.com/auth/shopify/callback",
  "https://descriptionfdprod.onrender.com/api/auth/callback"
]

[webhooks]
api_version = "2025-04"

[[webhooks.subscriptions]]
topics = ["app/uninstalled"]
uri = "/webhooks"
compliance_topics = [
  "customers/data_request",
  "customers/redact",
  "shop/redact"
]

[pos]
embedded = false
